# Generated by Django 3.2.8 on 2021-10-30 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user/pictures/', verbose_name='Profile Picture')),
                ('biography', models.TextField(blank=True, max_length=500, verbose_name='About me')),
                ('rides_taken', models.PositiveIntegerField(default=0, verbose_name='Rides taken')),
                ('rides_offered', models.PositiveIntegerField(default=0, verbose_name='Rides offered')),
                ('reputations', models.FloatField(default=5.0, help_text='Users reputations based on the rides taken and offered')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ('-created', '-modified'),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
