# Generated by Django 3.2.8 on 2021-10-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'get_latest_by': 'created', 'ordering': ['-rides_taken', '-rides_offered'], 'verbose_name': 'Circulo'},
        ),
    ]
